// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SearchPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class SearchRequest (
  val query: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SearchRequest {
      val query = pigeonVar_list[0] as String
      return SearchRequest(query)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      query,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SearchRequest
    return SearchPigeonPigeonUtils.deepEquals(this.query, other.query)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.query)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SearchReply (
  val result: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SearchReply {
      val result = pigeonVar_list[0] as String
      return SearchReply(result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      result,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SearchReply
    return SearchPigeonPigeonUtils.deepEquals(this.result, other.result)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.result)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NetWorkStatus (
  val name: String,
  val speed: String,
  val carrierName: String,
  val connectionType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NetWorkStatus {
      val name = pigeonVar_list[0] as String
      val speed = pigeonVar_list[1] as String
      val carrierName = pigeonVar_list[2] as String
      val connectionType = pigeonVar_list[3] as String
      return NetWorkStatus(name, speed, carrierName, connectionType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      speed,
      carrierName,
      connectionType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NetWorkStatus
    return SearchPigeonPigeonUtils.deepEquals(this.name, other.name) && SearchPigeonPigeonUtils.deepEquals(this.speed, other.speed) && SearchPigeonPigeonUtils.deepEquals(this.carrierName, other.carrierName) && SearchPigeonPigeonUtils.deepEquals(this.connectionType, other.connectionType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.name)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.speed)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.carrierName)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.connectionType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RamResult (
  val ramUsed: Double,
  val ramTotal: Double,
  val ramFree: Double,
  val pinStatus: Long,
  val tempStatus: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RamResult {
      val ramUsed = pigeonVar_list[0] as Double
      val ramTotal = pigeonVar_list[1] as Double
      val ramFree = pigeonVar_list[2] as Double
      val pinStatus = pigeonVar_list[3] as Long
      val tempStatus = pigeonVar_list[4] as Long
      return RamResult(ramUsed, ramTotal, ramFree, pinStatus, tempStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ramUsed,
      ramTotal,
      ramFree,
      pinStatus,
      tempStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RamResult
    return SearchPigeonPigeonUtils.deepEquals(this.ramUsed, other.ramUsed) && SearchPigeonPigeonUtils.deepEquals(this.ramTotal, other.ramTotal) && SearchPigeonPigeonUtils.deepEquals(this.ramFree, other.ramFree) && SearchPigeonPigeonUtils.deepEquals(this.pinStatus, other.pinStatus) && SearchPigeonPigeonUtils.deepEquals(this.tempStatus, other.tempStatus)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.ramUsed)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.ramTotal)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.ramFree)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.pinStatus)
    result = 31 * result + SearchPigeonPigeonUtils.deepHash(this.tempStatus)
    return result
  }
}
private open class SearchPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SearchRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SearchReply.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NetWorkStatus.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RamResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SearchRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SearchReply -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NetWorkStatus -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RamResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SearchApi {
  fun search(request: SearchRequest): SearchReply

  companion object {
    /** The codec used by SearchApi. */
    val codec: MessageCodec<Any?> by lazy {
      SearchPigeonPigeonCodec()
    }
    /** Sets up an instance of `SearchApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SearchApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.batterylevel.SearchApi.search$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SearchRequest
            val wrapped: List<Any?> = try {
              listOf(api.search(requestArg))
            } catch (exception: Throwable) {
              SearchPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NetworkApi {
  fun getNetworkInfo(): NetWorkStatus

  companion object {
    /** The codec used by NetworkApi. */
    val codec: MessageCodec<Any?> by lazy {
      SearchPigeonPigeonCodec()
    }
    /** Sets up an instance of `NetworkApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NetworkApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.batterylevel.NetworkApi.getNetworkInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNetworkInfo())
            } catch (exception: Throwable) {
              SearchPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RamApi {
  fun getRamInfo(): RamResult

  companion object {
    /** The codec used by RamApi. */
    val codec: MessageCodec<Any?> by lazy {
      SearchPigeonPigeonCodec()
    }
    /** Sets up an instance of `RamApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RamApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.batterylevel.RamApi.getRamInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRamInfo())
            } catch (exception: Throwable) {
              SearchPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
